//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAlClima
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clima
    {
        public int Id { get; set; }
        public string CLI_TEMPERATURA { get; set; }
        public string CLI_HUMEDAD { get; set; }
        public string CLI_VISIBILIDAD { get; set; }
    }
}
